no builæd

diff --git a/templates/create.sclspec.sh.j2 b/templates/create.sclspec.sh.j2
--- a/templates/create.sclspec.sh.j2
+++ b/templates/create.sclspec.sh.j2
@@ -14,7 +14,7 @@ touch /root/rpmbuild/SOURCES/LICENSE
 
 
 #META package
-echo "`date`: {{ organisation }} {{ project }}Build the metapackage."
+echo "`date`: {{ organisation }} {{ project }} Build the metapackage."
 
 cd  >/dev/null 2>&1
 if [[ -f /root/rpmbuild/RPMS/x86_64/{{ organisation }}-{{ project }}-runtime-{{ scl_version }}-{{ scl_release }}.el8.x86_64.rpm ]];
@@ -59,6 +59,7 @@ pip3 install setuptools >/dev/null 2>&1
 for DIR in `find /root/rpmbuild/SOURCES -maxdepth 2 -type d`
 do
     cd $DIR >/dev/null 2>&1
+    echo "`date`: {{ organisation }} {{ project }} Building script for $MYPKG"
     MYPKG=`echo $PWD|  rev|awk -F'/' '{ print $1 }'|rev`
     MYNAME=`echo $PWD|  rev|awk -F'/' '{ print $2 }'|rev`
     pip3 install --upgrade pip >/dev/null 2>&1
@@ -67,11 +68,15 @@ do
 
     if [[ -f setup.py ]];
     then
+      echo "`date`: {{ organisation }} {{ project }} Building script for $MYPKG"
       #loop until build dependecies are cleare
       #Try with python 3
+      COUNT="0"
       LOOP="YES"
-      while [[ $LOOP == "YES" ]];
+      while [ $LOOP == "YES" ] && [ $COUNT -lt 5 ] ;
       do
+        NEWCOUNT=`echo $COUNT |awk '{ print $1 + 1 }'`
+        COUNT=`echo $NEWCOUNT`
         python3 setup.py bdist_rpm --spec-only >/tmp/std.log 2>&1
         if [[ $? == 0 ]];
         then
@@ -92,38 +97,43 @@ do
 
         fi
       done
-      cat dist/*.spec > $DIR.spec
-      spec2scl $DIR.spec > $DIR.scl.pre.spec
-      awk '/record=INSTALLED_FILES/ { print; print "sed -i \"'s#^#/opt/{{ organisation }}/{{organisation}}-{{ project }}#'\" INSTALLED_FILES " ; next }1' $DIR.scl.pre.spec  > $DIR.scl.pre.spec.1
-      cat $DIR.scl.pre.spec.1 | sed 's#root=$RPM_BUILD_ROOT#root=$RPM_BUILD_ROOT/opt/{{ organisation }}/{{ organisation }}-{{ project }} #' > $DIR.scl.pre.spec.2
-      cat $DIR.scl.pre.spec.2 | sed "s#Source0:#Source0: http://repos.pip2scl.dk/SOURCES/${MYPKG}.tar.gz\nDELETELINE#"  |grep -v "^DELETELINE" > $DIR.scl.pre.spec.3
-      MYNAME=`echo $DIR | awk -F"${MYPKG}" '{ print $1 }'`
-      cat $DIR.scl.pre.spec.3 | sed "s#setup -n #setup -n ${MYPKG}\nDELETELINE#" |grep -v "^DELETELINE" > /root/rpmbuild/SPECS/${ORG}.${PROJECT}.${MYPKG}.scl.spec
-      scp /root/rpmbuild/SPECS/${ORG}.${PROJECT}.${MYPKG}.scl.spec root@repos.pip2scl.dk:/usr/share/nginx/html/SPECS >/dev/null 2>&1
-      
-      cd .. >/dev/null 2>&1
-      tar -czf /root/rpmbuild/SOURCES/$MYPKG.tar.gz $MYPKG
-      scp  /root/rpmbuild/SOURCES/$MYPKG.tar.gz root@repos.pip2scl.dk:/usr/share/nginx/html/SOURCES >/dev/null 2>&2
-      SCRIPT="build_{{ organisation }}_{{ project }}.scl.sh"
-      echo "#!/usr/bin/env bash" >  /tmp/${SCRIPT}
-      echo "rpmbuild -ba /root/rpmbuild/SPECS/${ORG}.${PROJECT}.${MYPKG}.scl.spec  --define \"scl {{ organisation }}-{{ project }}\" >/dev/null 2>&1" >> $SCRIPT
-      echo "if [[ $? == 0 ]];" >> $SCRIPT
-      echo "then" >> $SCRIPT
-      echo "  echo \"`date`: {{ organisation }} {{ project }} package build with python3\"" >> $SCRIPT
-
-      awk '/Group: / { print; print "" ; next }1' /root/{{ organisation }}.{{ project }}.project.spec  > /root/{{ organisation }}.{{ project }}.project.spec.add
-      mv /root/{{ organisation }}.{{ project }}.project.spec.add /root/{{ organisation }}.{{ project }}.project.spec
-      echo "else"   >> $SCRIPT
-      echo "  echo \"`date`: {{ organisation }} {{ project }} package build failledi with python3\"" >> $SCRIPT
-      echo "exit 1" >> $SCRIPT
-      echo "fi" >> $SCRIPT
-      scp $SCRIPT  root@repos.pip2scl.dk:/usr/share/nginx/html/SCRIPTS >/dev/null 2>&1
-      if [[ $? == 0 ]];
+      if [[ $LOOP == NO ]];
       then
-        echo "`date`: {{ organisation }} {{ project }} SCL build script for $MYPKG populated"
-      else
-        echo "`date`: {{ organisation }} {{ project }} SCL build script for $MYPKG failed to be populated"
-      fi 
+        cat dist/*.spec > $DIR.spec
+        spec2scl $DIR.spec > $DIR.scl.pre.spec
+        awk '/record=INSTALLED_FILES/ { print; print "sed -i \"'s#^#/opt/{{ organisation }}/{{organisation}}-{{ project }}#'\" INSTALLED_FILES " ; next }1' $DIR.scl.pre.spec  > $DIR.scl.pre.spec.1
+        cat $DIR.scl.pre.spec.1 | sed 's#root=$RPM_BUILD_ROOT#root=$RPM_BUILD_ROOT/opt/{{ organisation }}/{{ organisation }}-{{ project }} #' > $DIR.scl.pre.spec.2
+        cat $DIR.scl.pre.spec.2 | sed "s#Source0:#Source0: http://repos.pip2scl.dk/SOURCES/${MYPKG}.tar.gz\nDELETELINE#"  |grep -v "^DELETELINE" > $DIR.scl.pre.spec.3
+        MYNAME=`echo $DIR | awk -F"${MYPKG}" '{ print $1 }'`
+        cat $DIR.scl.pre.spec.3 | sed "s#setup -n #setup -n ${MYPKG}\nDELETELINE#" |grep -v "^DELETELINE" > /root/rpmbuild/SPECS/${ORG}.${PROJECT}.${MYPKG}.scl.spec
+        scp /root/rpmbuild/SPECS/${ORG}.${PROJECT}.${MYPKG}.scl.spec root@repos.pip2scl.dk:/usr/share/nginx/html/SPECS >/dev/null 2>&1
+      
+        cd .. >/dev/null 2>&1
+        tar -czf /root/rpmbuild/SOURCES/$MYPKG.tar.gz $MYPKG
+        scp  /root/rpmbuild/SOURCES/$MYPKG.tar.gz root@repos.pip2scl.dk:/usr/share/nginx/html/SOURCES >/dev/null 2>&2
+        SCRIPT="build_{{ organisation }}_{{ project }}.scl.sh"
+        echo "#!/usr/bin/env bash" >  /tmp/${SCRIPT}
+        echo "rpmbuild -ba /root/rpmbuild/SPECS/${ORG}.${PROJECT}.${MYPKG}.scl.spec  --define \"scl {{ organisation }}-{{ project }}\" >/dev/null 2>&1" >> $SCRIPT
+        echo "if [[ $? == 0 ]];" >> $SCRIPT
+        echo "then" >> $SCRIPT
+        echo "  echo \"`date`: {{ organisation }} {{ project }} package build with python3\"" >> $SCRIPT
+
+        awk '/Group: / { print; print "" ; next }1' /root/{{ organisation }}.{{ project }}.project.spec  > /root/{{ organisation }}.{{ project }}.project.spec.add
+        mv /root/{{ organisation }}.{{ project }}.project.spec.add /root/{{ organisation }}.{{ project }}.project.spec
+        echo "else"   >> $SCRIPT
+        echo "  echo \"`date`: {{ organisation }} {{ project }} package build failledi with python3\"" >> $SCRIPT
+        echo "exit 1" >> $SCRIPT
+        echo "fi" >> $SCRIPT
+        scp $SCRIPT  root@repos.pip2scl.dk:/usr/share/nginx/html/SCRIPTS >/dev/null 2>&1
+        if [[ $? == 0 ]];
+        then
+          echo "`date`: {{ organisation }} {{ project }} SCL build script for $MYPKG populated"
+        else
+          echo "`date`: {{ organisation }} {{ project }} SCL build script for $MYPKG failed to be populated"
+        fi 
+      fi
+    else
+      echo "`date`: {{ organisation }} {{ project }} $MYPKG failed to be build and is excluded from the scl - "
     fi
     cd - >/dev/null 2>&1 
 done
