dependencies calculated

diff --git a/templates/create.sclspec.sh.j2 b/templates/create.sclspec.sh.j2
--- a/templates/create.sclspec.sh.j2
+++ b/templates/create.sclspec.sh.j2
@@ -140,6 +140,13 @@ do
         if [[ $? == 0 ]];
         then
           echo "`date`: {{ organisation }} {{ project }} SCL build script for $MYPKG populated"
+          scp /root/rpmbuild/SPECS/${ORG}.${PROJECT}.${MYPKG}.scl.spec   root@repos.pip2scl.dk:/usr/share/nginx/html/SPECS >/dev/null 2>&1
+          if [[ $? == 0 ]];
+          then
+            echo "`date`: {{ organisation }} {{ project }} SCL build SPEC file for $MYPKG populated"
+          else  
+            echo "`date`: {{ organisation }} {{ project }} SCL build SPEC file for $MYPKG failed"
+          fi
         else
           echo "`date`: {{ organisation }} {{ project }} SCL build script for $MYPKG failed to be populated"
         fi 
