scl release

diff --git a/templates/create.sclspec.sh.j2 b/templates/create.sclspec.sh.j2
--- a/templates/create.sclspec.sh.j2
+++ b/templates/create.sclspec.sh.j2
@@ -14,7 +14,15 @@ else
   exit 1
 fi
 
-rpm -Uhd /root/rpmbuild/RPMS/x86_64/{{ organisation }}-{{ project }}-runtime-{{ scl_version }}-{{ scl_release }}.el8.x86_64.rpm
+rpm -i /root/rpmbuild/RPMS/x86_64/{{ organisation }}-{{ project }}-runtime-{{ scl_version }}-{{ scl_release }}.el8.x86_64.rpm
+if [[ $? == 0 ]];
+then
+  echo "`date`: SCL metapackage installed ok"
+else
+  echo "`date`: SCL metapackage install failed"
+  exit 1
+fi
+
 
 pip3 install --upgrade pip >/dev/null 2>&1
 pip3 install spec2scl
@@ -69,7 +77,7 @@ do
       cd ..
       tar -czf /root/rpmbuild/SOURCES/$MYPKG.tar.gz $MYPKG
       scp  /root/rpmbuild/SOURCES/$MYPKG.tar.gz root@repos.pip2scl.dk:/usr/share/nginx/html/SOURCES
-      rpmbuild -ba /root/rpmbuild/SPECS/${ORG}.${PROJECT}.${MYPKG}.scl.spec  --define "scl miracle-pip2scl-demo"
+      rpmbuild -ba /root/rpmbuild/SPECS/${ORG}.${PROJECT}.${MYPKG}.scl.spec  --define "scl {{ organisation }}-{{ project }}"
     fi
     cd -
 done
